[tool.poetry]
name = "gui-python-pygobject-gtk4"
version = "0.2.0"
description = "Criando interfaces gráficas com a linguagem de programação Python (PyGObject) e o toolkit gráfico Gtk 4"
authors = ["Renato Cruz <zkpcvm6dz@mozmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://gtk.justcode.com.br/"
documentation = "https://gtk.justcode.com.br/"
repository = "https://github.com/natorsc/gui-python-pygobject-gtk4"
keywords = ["python", "pygobject", "gtk", "gtk 4", "libadwaita", "blueprint", "gnome", "gnome builder"]

classifiers = [
    "Topic :: Software Development",
    "Topic :: Desktop Environment",
    "Topic :: Desktop Environment :: Gnome",
    "Environment :: X11 Applications :: GTK",
    "Environment :: X11 Applications :: Gnome",
    "Operating System :: Microsoft",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.10"
PyGObject = "^3.42.2"

[tool.poetry.group.dev.dependencies]
pylint = "^2.15.2"
autopep8 = "^1.7.0"
PyGObject-stubs = "^1.0.0"

[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"
sphinx-copybutton = "^0.5.0"
sphinx-inline-tabs = "^2022.1.2b11"
sphinxext-opengraph = "^0.6.3"
sphinx-sitemap = "^2.2.0"
furo = "^2022.9.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
