[project]
name = "pygobject-gtk"
version = "0.0.1"
description = "Criando interfaces gráficas com Python (PyGObject) e GTK"
authors = [
    {name = "Renato Cruz", email = "natorsc@gmail.com"},
]
dependencies = [
    "pygobject>=3.46.0",
]
requires-python = ">=3.10,<3.13"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
docs = [
    "sphinx>=7.2.6",
    "sphinx-copybutton>=0.5.2",
    "sphinx-inline-tabs>=2023.4.21",
    "sphinxext-opengraph>=0.9.0",
    "sphinx-sitemap>=2.5.1",
    "furo>=2023.9.10",
]
[tool.pdm.dev-dependencies]
dev = [
    "pylint>=3.0.2",
    "autopep8>=2.0.4",
    "pygobject-stubs>=2.10.0",
]
